[package]
name = "anmitsu"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"

[[bin]]
name = "lc-cycle-detection"
path = "src/bin/library_checker/cycle_detection.rs"

[[bin]]
name = "lc-shortest-path"
path = "src/bin/library_checker/shortest_path.rs"

[[bin]]
name = "lc-scc"
path = "src/bin/library_checker/scc.rs"

[[bin]]
name = "lc-two-sat"
path = "src/bin/library_checker/two_sat.rs"

[[bin]]
name = "lc-eulerian-trail-directed"
path = "src/bin/library_checker/eulerian_trail_directed.rs"

[[bin]]
name = "lc-minimum-spanning-tree"
path = "src/bin/library_checker/minimum_spanning_tree.rs"

[[bin]]
name = "lc-assignment"
path = "src/bin/library_checker/assignment.rs"

[[bin]]
name = "lc-bipartitematching"
path = "src/bin/library_checker/bipartitematching.rs"

[[bin]]
name = "lc-lca"
path = "src/bin/library_checker/lca.rs"

[[bin]]
name = "lc-lca-by-euler-tour"
path = "src/bin/library_checker/lca_by_euler_tour.rs"

[[bin]]
name = "lc-vertex-add-path-sum"
path = "src/bin/library_checker/vertex_add_path_sum.rs"

[[bin]]
name = "lc-convolution-mod"
path = "src/bin/library_checker/convolution_mod.rs"

[[bin]]
name = "lc-inv-of-formal-power-series"
path = "src/bin/library_checker/inv_of_formal_power_series.rs"

[[bin]]
name = "lc-exp-of-formal-power-series"
path = "src/bin/library_checker/exp_of_formal_power_series.rs"

[[bin]]
name = "lc-log-of-formal-power-series"
path = "src/bin/library_checker/log_of_formal_power_series.rs"

[[bin]]
name = "lc-pow-of-formal-power-series"
path = "src/bin/library_checker/pow_of_formal_power_series.rs"

[[bin]]
name = "lc-inv-of-formal-power-series-sparse"
path = "src/bin/library_checker/inv_of_formal_power_series_sparse.rs"

[[bin]]
name = "lc-exp-of-formal-power-series-sparse"
path = "src/bin/library_checker/exp_of_formal_power_series_sparse.rs"

[[bin]]
name = "lc-log-of-formal-power-series-sparse"
path = "src/bin/library_checker/log_of_formal_power_series_sparse.rs"

[[bin]]
name = "lc-pow-of-formal-power-series-sparse"
path = "src/bin/library_checker/pow_of_formal_power_series_sparse.rs"

[[bin]]
name = "lc-kth-term-of-linearly-recurrent-sequence"
path = "src/bin/library_checker/kth_term_of_linearly_recurrent_sequence.rs"

[[bin]]
name = "lc-partition-function"
path = "src/bin/library_checker/partition_function.rs"

[[bin]]
name = "lc-sharp-p-subset-sum"
path = "src/bin/library_checker/sharp_p_subset_sum.rs"

[[bin]]
name = "lc-product-of-polynomial-sequence"
path = "src/bin/library_checker/product_of_polynomial_sequence.rs"

[[bin]]
name = "ac-fps24-k-permutation"
path = "src/bin/atcoder/fps24_k_permutation.rs"

[[bin]]
name = "ac-fps24-l-permutation2"
path = "src/bin/atcoder/fps24_l_permutation2.rs"

[[bin]]
name = "ac-fps24-m-connected-graph"
path = "src/bin/atcoder/fps24_m_connected_graph.rs"

[[bin]]
name = "ac-fps24-c-sequence"
path = "src/bin/atcoder/fps24_c_sequence.rs"

[[bin]]
name = "ac-fps24-i-score"
path = "src/bin/atcoder/fps24_i_score.rs"

[[bin]]
name = "ac-fps24-a-snack"
path = "src/bin/atcoder/fps24_a_snack.rs"

[[bin]]
name = "ac-fps24-b-tuple-of-integers"
path = "src/bin/atcoder/fps24_b_tuple_of_integers.rs"

[[bin]]
name = "ac-fps24-d-sequence2"
path = "src/bin/atcoder/fps24_d_sequence2.rs"

[[bin]]
name = "ac-fps24-e-sequence3"
path = "src/bin/atcoder/fps24_e_sequence3.rs"

[[bin]]
name = "ac-fps24-n-coin2"
path = "src/bin/atcoder/fps24_n_coin2.rs"

[[bin]]
name = "ac-abc422-g-balls-and-boxes"
path = "src/bin/atcoder/abc422_g_balls_and_boxes.rs"

[[bin]]
name = "aoj-alds1-11-b-depth-first-search"
path = "src/bin/aoj/alds1_11_b_depth_first_search.rs"

[[bin]]
name = "aoj-alds1-11-c-breadth-first-search"
path = "src/bin/aoj/alds1_11_c_breadth_first_search.rs"

[[bin]]
name = "aoj-grl-1-b-single-source-shortest-path"
path = "src/bin/aoj/grl_1_b_single_source_shortest_path.rs"

[[bin]]
name = "aoj-grl-1-c-all-pairs-shortest-path"
path = "src/bin/aoj/grl_1_c_all_pairs_shortest_path.rs"

[[bin]]
name = "aoj-grl-1-c-all-pairs-shortest-path-johnson"
path = "src/bin/aoj/grl_1_c_all_pairs_shortest_path_johnson.rs"

[[bin]]
name = "aoj-grl-4-b-topological-sort"
path = "src/bin/aoj/grl_4_b_topological_sort.rs"

[[bin]]
name = "ac-abc176-d-wizard-in-maze"
path = "src/bin/atcoder/abc176_d_wizard_in_maze.rs"

[[bin]]
name = "ac-abc075-c-bridge"
path = "src/bin/atcoder/abc075_c_bridge.rs"

[[bin]]
name = "ac-abc209-d-collision"
path = "src/bin/atcoder/abc209_d_collision.rs"

[[bin]]
name = "ac-typical90-u-come-back-in-one-piece"
path = "src/bin/atcoder/typical90_u_come_back_in_one_piece.rs"

[[bin]]
name = "ac-typical90-m-passing"
path = "src/bin/atcoder/typical90_m_passing.rs"

[[bin]]
name = "ac-typical90-aq-maze-challenge-with-lack-of-sleep"
path = "src/bin/atcoder/typical90_aq_maze_challenge_with_lack_of_sleep.rs"

[[bin]]
name = "ac-typical90-bs-fuzzy-priority"
path = "src/bin/atcoder/typical90_bs_fuzzy_priority.rs"

[[bin]]
name = "ac-arc085-e-mul"
path = "src/bin/atcoder/arc085_e_mul.rs"

[[bin]]
name = "ac-typical90-an-get-more-money"
path = "src/bin/atcoder/typical90_an_get_more_money.rs"

[[bin]]
name = "ac-abc294-g-distance-queries-on-a-tree"
path = "src/bin/atcoder/abc294_g_distance_queries_on_a_tree.rs"

[[bin]]
name = "ac-abc326-g-unlock-achievement"
path = "src/bin/atcoder/abc326_g_unlock_achievement.rs"

[[bin]]
name = "ac-abc225-g-x"
path = "src/bin/atcoder/abc225_g_x.rs"

[[bin]]
name = "ac-abc193-f-zebraness"
path = "src/bin/atcoder/abc193_f_zebraness.rs"

[[bin]]
name = "poj-poj2987-firing"
path = "src/bin/poj/poj2987_firing.rs"

[[bin]]
name = "spoj-qtree"
path = "src/bin/spoj/qtree.rs"

[[bin]]
name = "spoj-qtree2"
path = "src/bin/spoj/qtree2.rs"

[[bin]]
name = "yuki-yuki650-matrix-tree-query"
path = "src/bin/yukicoder/yuki650_matrix_tree_query.rs"

[[bin]]
name = "yuki-yuki2713-just-solitaire"
path = "src/bin/yukicoder/yuki2713_just_solitaire.rs"

[[bin]]
name = "cf-cf1082g-petya-and-graph"
path = "src/bin/codeforces/cf1082g_petya_and_graph.rs"

[[bin]]
name = "ac-practice2-d-maxflow"
path = "src/bin/atcoder/practice2_d_maxflow.rs"

[[bin]]
name = "ac-abc406-f-compare-tree-weights"
path = "src/bin/atcoder/abc406_f_compare_tree_weights.rs"

[[bin]]
name = "ac-abc187-e-through-path"
path = "src/bin/atcoder/abc187_e_through_path.rs"

[[bin]]
name = "ac-typical90-am-tree-distance"
path = "src/bin/atcoder/typical90_am_tree_distance.rs"

[[bin]]
name = "lc-tree-diameter"
path = "src/bin/library_checker/tree_diameter.rs"

[[bin]]
name = "lc-jump-on-tree"
path = "src/bin/library_checker/jump_on_tree.rs"

[[bin]]
name = "aoj-grl-5-a-diameter-of-a-tree"
path = "src/bin/aoj/grl_5_a_diameter_of_a_tree.rs"

[[bin]]
name = "lc-vertex-set-path-composite"
path = "src/bin/library_checker/vertex_set_path_composite.rs"

[[bin]]
name = "bj-bj15480-lca-and-query"
path = "src/bin/baekjoon/bj15480_lca_and_query.rs"

[[bin]]
name = "poj-poj1741-tree"
path = "src/bin/poj/poj1741_tree.rs"

[[bin]]
name = "cc-talca"
path = "src/bin/codechef/talca.rs"

[[bin]]
name = "ac-abc035-c-othello"
path = "src/bin/atcoder/abc035_c_othello.rs"

[[bin]]
name = "lc-range-affine-range-sum"
path = "src/bin/library_checker/range_affine_range_sum.rs"

[dev-dependencies]
rstest = "0.26.1"
